---

x-base: &base
  image: ${registry}${testnet}:latest
  restart: on-failure
  build:
    context: "../../"
    dockerfile: "Dockerfile.compiled"
    args:
      CARDANO_NODE_VERSION: "10.2.1"

x-env: &env
  POOL_ID: "0" # Placeholder required for override

services:
  p1:
    <<: *base
    container_name: p1
    hostname: p1.example
    volumes:
      - p1:/opt/cardano-node/data
    ports:
      - "3001:3001"
    environment:
      <<: *env
      POOL_ID: "1"

  p2:
    <<: *base
    container_name: p2
    hostname: p2.example
    volumes:
      - p2:/opt/cardano-node/data
    ports:
      - "3002:3001"
    environment:
      <<: *env
      POOL_ID: "2"
      PEER_SHARING: "false"

  p3:
    <<: *base
    container_name: p3
    hostname: p3.example
    volumes:
      - p3:/opt/cardano-node/data
    ports:
      - "3003:3001"
    environment:
      <<: *env
      POOL_ID: "3"

  s1:
    image: ${registry}${testnet}_sidecar:latest
    restart: on-failure
    container_name: s1
    hostname: s1.example
    environment:
      POOLS: "3"

volumes:
  p1:
  p2:
  p3:
