services:
  anti-agent:
    image: cardano-foundation/anti-agent:latest
    secrets:
      - agent-wallet
      - secrets
      - source: docker
        target: /run/secrets/docker/config.json
    environment:
      - ANTI_MPFS_HOST=https://mpfs.plutimus.com
      - ANTI_WALLET_FILE=/run/secrets/agent-wallet
      - ANTI_TOKEN_ID=21c523c3b4565f1fc1ad7e54e82ca976f60997d8e7e9946826813fabf341069b
      - ANTI_SECRETS_FILE=/run/secrets/secrets
      - ANTI_WAIT=240
      - ANTI_ANTITHESIS_USER=cardano
      - DOCKER_CONFIG=/run/secrets/docker
    restart:
      always
    privileged: true
    volumes:
      - tmp:/tmp
         # Mount CA certificates, curl seems not to find them when the pkgs.cacert is included in the image
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /var/run/docker.sock:/var/run/docker.sock
secrets:
  agent-wallet:
    file: /secrets/anti-agent/agent.json # Path to a file containing the wallet
  secrets:
    file: /secrets/anti-agent/secrets.yaml # Path to a file containing the secrets
  docker:
    file: /secrets/anti-agent/docker/config.json # Path to a file containing Docker config (for private registries)

volumes:
  tmp:

### Keys of the secrets.yaml file:
  # agentEmail: # Email address where url links are received
  # agentEmailPassword: # App password for the email account
  # githubPAT: # GitHub Personal Access Token
  # trustedRequesters:
  #   - requester1
  #   - requester2
  # antithesisPassword: # Password for Antithesis registry and Docker image