services:
  anti-oracle:
    image: cardano-foundation/anti-oracle:latest
    secrets:
      - oracle-wallet
      - secrets
    environment:
      - ANTI_MPFS_HOST=https://mpfs.plutimus.com
      - ANTI_WALLET_FILE=/run/secrets/oracle-wallet
      - ANTI_TOKEN_ID=21c523c3b4565f1fc1ad7e54e82ca976f60997d8e7e9946826813fabf341069b
      - ANTI_SECRETS_FILE=/run/secrets/secrets
      - ANTI_WAIT=240
    restart:
      always
    volumes:
      - tmp:/tmp
secrets:
  oracle-wallet:
    file: /secrets/anti-oracle/oracle.json # Path to a file containing the wallet
  secrets:
    file: /secrets/anti-oracle/secrets.yaml # Path to a file containing the secrets

volumes:
  tmp: